FROM python:3.10-slim-buster

WORKDIR /backend-flask

COPY requirement.txt requirements.txt
# install the python libraries used for the app
RUN pip3 install -r requirements.txt

COPY . .
# first period . -/backend-flask (outside container)
# second period . /backend-flask (inside container)
ENV FLASK_ENV=development
# set the environment variable
# nside container
EXPOSE ${PORT}
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=4567"]
#